# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ObjectDetectorPlugin
                                 A QGIS plugin
 This plugin can detect objects from satellite imagery with help of modern AI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-04-15
        copyright            : (C) 2022 by Skeptlk
        email                : sceptlc@bk.ru
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ObjectDetectorPlugin class from file ObjectDetectorPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .object_detector_plugin import ObjectDetectorPlugin
    return ObjectDetectorPlugin(iface)
